### ISSUE TITLE
1.19.2 version of this Mod crashes with Forge

### ISSUE THREAD

**Issue by ModernGamingWorld** [konwboj/Tumbleweed#31]
[crash-2023-01-26_16.53.59-client.txt](https://github.com/konwboj/Tumbleweed/files/10514065/crash-2023-01-26_16.53.59-client.txt)

**Comment by konwboj** [comment]
Related to #30, I only support 1.19.3

**Comment by NixityNull** [comment]
I don't understand why you can't take a moment to fix the problem on 1.19.2? It would be understandable if you didn't want to add newer versions' content back to an older version, but this is a matter of fixing a bug that makes the mod completely unplayable on that version! The mod is already there, it's just a matter of fixing the same issue in the same way you've already done. I don't know if it's as simple as copy-pasting a line of code or if you have to rework the same equations slightly to fix it for that version, but given that the only changes made between 1.19.2 and 1.19.3 are minor bugfixes and commands that are irrelevant to the mod, I don't think it would be that much of a Sisyphean task to fix it.

**Comment by NixityNull** [comment]
I love this mod because it's a small touch to desert biomes that goes a long way, as well as a renewable source of items. I don't NEED this mod, but it feels a little bit empty without it, and while I had started using 1.19.3 when I first started modding 1.19, i ended up moving back to 1.19.2 because so many great mods have yet to update, including origins, farmers' delight, and all of team abnormals' mods

**Comment by konwboj** [comment]
Pushed an update to CurseForge
